name: nutter-test

on: [push]

env:
  DATABRICKS_PATH: /Shared/nutter-demo

jobs:
  nutter-test:
    environment: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Tools
        run: pip install nutter databricks-cli

      - name: Deploy Notebooks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks workspace rm -r $DATABRICKS_PATH
          databricks workspace mkdirs $DATABRICKS_PATH
          databricks workspace import_dir --overwrite notebooks $DATABRICKS_PATH/notebooks
          databricks workspace import_dir --overwrite tests $DATABRICKS_PATH/tests

      - name: Run Nutter tests
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          nutter run $DATABRICKS_PATH/tests/demo-nut* --cluster_id ${{ secrets.DATABRICKS_CLUSTER_ID }} --junit_report

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/test-*.xml'
